# Generated by Django 5.0.4 on 2024-09-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls_managing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrator",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
